# Generated by Django 4.2.20 on 2025-03-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_user_photo_url_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.ImageField(default='images/krishtec.jpg', upload_to='images/'),
        ),
    ]
