# Generated by Django 4.2.20 on 2025-03-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_topic_domain_type_topic_tech_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='practice',
            name='duration',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='test',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=900),
        ),
    ]
