# Generated by Django 4.2.20 on 2025-03-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_practice_attempts_practice_duration_test_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceoption',
            name='option1_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practiceoption',
            name='option2_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practiceoption',
            name='option3_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practiceoption',
            name='option4_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='question_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testoption',
            name='option1_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testoption',
            name='option2_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testoption',
            name='option3_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testoption',
            name='option4_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
