# Generated by Django 4.2.20 on 2025-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_practiceoption_option1_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='explanation_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='explanation_img',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
