# Generated by Django 5.2 on 2025-04-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_practicequestion_explanation_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image_url',
            field=models.ImageField(default='topics/course.png', upload_to='topics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='tech', max_length=255),
        ),
    ]
